version: '3'
services:
  pyspark-devenv-standalone:
    image: ornrocha/pyspark-devenv-standalone:${TAG:-latest}
    container_name: pyspark-devenv-standalone-vscode-wks
    environment:
      GIT_USERNAME: ${GIT_USERNAME:-default}
      GIT_EMAIL: ${GIT_EMAIL:-default}
      JUPYTER_PORT: ${JUPYTER_PORT:-8888}
      JUPYTER_PASSWORD: ${JUPYTER_PASSWORD}
      JUPYTER_ALLOW_ORIGIN: ${JUPYTER_ALLOW_ORIGIN:-0.0.0.0}
      JUPYTER_SPARk_MEMORY: ${JUPYTER_SPARk_MEMORY:-2g}
      JUPYTER_SPARK_CORES: ${JUPYTER_SPARK_CORES:-2}
      DISABLE_JUPYTER: ${DISABLE_JUPYTER:-0}
      SPARK_EXECUTOR_MEMORY: ${SPARK_EXECUTOR_MEMORY:-2g}
      SPARK_DRIVER_MEMORY: ${SPARK_DRIVER_MEMORY:-4g}

    hostname: spark-master

    volumes:
      - ../workspace:/home/devuser/workspace
      - ../data:/mnt/data
      - ../external_modules:/home/devuser/external_pythonpath
      - ../extra_jars:/home/devuser/.extra_jars
      - pyspark-devenv-standalone-vscode-wks-ssh-keys:/home/devuser/.ssh:rw
      - pyspark-devenv-standalone-vscode-wks-spark-jars:/home/devuser/.ivy2:rw
      - pyspark-devenv-standalone-vscode-wks-spark-cache:/home/devuser/.spark_local_dir:rw
      - pyspark-devenv-standalone-vscode-wks-pyenv:/home/devuser/devenv:rw
      - pyspark-devenv-standalone-vscode-wks-spark-logs:/opt/spark/spark-events:rw
    ports:
      - ${JUPYTER_PORT:-8888}:${JUPYTER_PORT:-8888}
      - 8080:8080
      - 7077:7077

  pyspark-devenv-worker-1:
    image: ornrocha/pyspark-devenv-worker:${TAG:-latest}
    container_name: pyspark-devenv-worker-1-vscode
    ports:
      - 8081:8081
    depends_on:
      - pyspark-devenv-standalone
    environment:
      SPARK_WORKER_CORES: ${SPARK_WORKER_CORES:-2}
      SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY:-4g}

    volumes:
      - ../workspace:/home/devuser/workspace
      - ../data:/mnt/data
      - ../external_modules:/home/devuser/external_pythonpath
      - ../extra_jars:/home/devuser/.extra_jars
      - pyspark-devenv-standalone-vscode-wks-spark-jars:/home/devuser/.ivy2
      - pyspark-devenv-standalone-vscode-wks-spark-cache:/home/devuser/.spark_local_dir:rw           
      - pyspark-devenv-standalone-vscode-wks-pyenv:/home/devuser/devenv
      - pyspark-devenv-standalone-vscode-wks-spark-logs:/opt/spark/spark-events:rw

  pyspark-devenv-worker-2:
    image: ornrocha/pyspark-devenv-worker:${TAG:-latest}
    container_name: pyspark-devenv-worker-2-vscode
    ports:
      - 8082:8081

    depends_on:
      - pyspark-devenv-standalone
    environment:
      SPARK_WORKER_CORES: ${SPARK_WORKER_CORES:-2}
      SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY:-4g}

    volumes:
      - ../workspace:/home/devuser/workspace
      - ../data:/mnt/data
      - ../external_modules:/home/devuser/external_pythonpath
      - ../extra_jars:/home/devuser/.extra_jars
      - pyspark-devenv-standalone-vscode-wks-spark-jars:/home/devuser/.ivy2
      - pyspark-devenv-standalone-vscode-wks-spark-cache:/home/devuser/.spark_local_dir:rw           
      - pyspark-devenv-standalone-vscode-wks-pyenv:/home/devuser/devenv
      - pyspark-devenv-standalone-vscode-wks-spark-logs:/opt/spark/spark-events:rw

  pyspark-devenv-history:
    image: ornrocha/pyspark-devenv-history:${TAG:-latest}
    container_name: pyspark-devenv-history-vscode
    environment:
      HISTORY_CLEANER_INTERVAL: ${HISTORY_CLEANER_INTERVAL:-1d}
      HISTORY_MAX_AGE: ${HISTORY_MAX_AGE:-7d}
    depends_on:
      - pyspark-devenv-standalone
    volumes:
      - pyspark-devenv-standalone-vscode-wks-spark-logs:/opt/spark/spark-events:rw
    ports:
      - 18080:18080         

volumes:
  pyspark-devenv-standalone-vscode-wks-pyenv:
  pyspark-devenv-standalone-vscode-wks-ssh-keys:
  pyspark-devenv-standalone-vscode-wks-spark-jars:
  pyspark-devenv-standalone-vscode-wks-spark-logs:
  pyspark-devenv-standalone-vscode-wks-spark-cache:
